server:
  port: 8080
spring:
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:file:./config.properties
  application:
    name: gateway-server
  cloud:
    config:
      username: ${security.name}
      password: ${security.password}
      name: gateway-server
      profile: dev
      retry:
        max-attempts: 1
        max-interval: 1000
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**, /api/auth/v3/api-docs
        - id: owner
          uri: lb://owner
          predicates:
            - Path=/api/v1/owner/**, /api/owner/v3/api-docs
        - id: client
          uri: lb://client
          predicates:
            - Path=/api/v1/client/**, /api/client/v3/api-docs
        - id: employee
          uri: lb://employee
          predicates:
            - Path=/api/v1/employee/**, /api/employee/v3/api-docs
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/auth/v3/api-docs
        name: Auth Service
      - url: /api/owner/v3/api-docs
        name: Owner Service
      - url: /api/client/v3/api-docs
        name: Client Service
      - url: /api/employee/v3/api-docs
        name: Employee Service
