server:
  servlet:
    context-path: /api/v1
  port: 9094

spring:
  application:
    name: store-management
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin
      name: db,general,sotore-management
      profile: local
