server:
  port: 9093

spring:
  application:
    name: client
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:file:./config.properties
  cloud:
    config:
      username: ${security.name}
      password: ${security.password}
      name: db,general,client
      profile: local
      retry:
        max-attempts: 1
        max-interval: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
