server:
  servlet:
    context-path: /api/v1
  port: 9093

spring:
  application:
    name: client
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin
      name: db,general,client
      profile: local
      retry:
        max-attempts: 1
        max-interval: 1000
