server:
  port: 9094

spring:
  application:
    name: employee
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin
      name: db,general,employee
      profile: local
      retry:
        max-attempts: 1
        max-interval: 1000
