server:
  port: 8762

spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin
      name: general
      profile: local
      retry:
        max-attempts: 1
        max-interval: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
