server:
  port: 9091
spring:
  application:
    name: auth
  config:
    import: optional:configserver:http://localhost:8888
  security:
    auth0:
      domain: https://dev-9pn-820c.us.auth0.com
      client-id: ikWPpY8zw0AkwBUhsKj6rRyqdX2m7Isi
      client-secret: KPrWBYxz754nn-4pJKUnU8DZnmGpPoU-0dCpQg_fr2ysq0AbIw-9NLxoO4cTec-W
openapi:
  service:
    title: auth-service doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/auth/v3/api-docs
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
