server:
  port: 9091
spring:
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:file:./config.properties
  application:
    name: auth
  cloud:
    config:
      username: ${security.name}
      password: ${security.password}
      name: general, auth
      profile: dev
      retry:
        max-attempts: 1
        max-interval: 1000
openapi:
  service:
    title: auth-service doc
    version: 1.0.0
    url-gateway: http://localhost:8080
    url-auth: http://localhost:9091
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /api/auth/v3/api-docs
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
