server:
  servlet:
    context-path: /api/v1
  port: 9092

spring:
  application:
    name: appoitment
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin
      name: db,general,appointment
      profile: local
